-- AlterTable
ALTER TABLE "OpeningTime" ALTER COLUMN "midOpenTime" SET DATA TYPE TIME(0),
ALTER COLUMN "midCloseTime" SET DATA TYPE TIME(0),
ALTER COLUMN "openTime" DROP NOT NULL,
ALTER COLUMN "closeTime" DROP NOT NULL;
